<a href="https://colab.research.google.com/github/Deveshjd/ML-Notebooks/blob/main/ML1-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import numpy as np
import pandas as pd

In [43]:
df = pd.read_csv("/content/sample_data/housing 1.csv")

In [44]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [45]:
x = df.drop('median_house_value',axis=1)
y = df['median_house_value']

In [46]:
x.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,NEAR BAY

In [47]:
y.head()

0    452600.0
1    358500.0
2    352100.0
3    341300.0
4    342200.0
Name: median_house_value, dtype: float64

In [48]:
cat_col_list = x.select_dtypes("object").columns.to_list()

In [49]:
num_col_list = x.select_dtypes(["int", "float"]).columns.to_list()

In [50]:
cat_col_list

['ocean_proximity']

In [51]:
num_col_list

['longitude',
 'latitude',
 'housing_median_age',
 'total_rooms',
 'total_bedrooms',
 'population',
 'households',
 'median_income']

In [52]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [53]:
Num_pipeline = Pipeline(
    steps = [
        ("Impute", SimpleImputer(strategy = "median")),
        ("Scale", StandardScaler())
    ]
)

Num_pipeline

Pipeline(steps=[('Impute', SimpleImputer(strategy='median')),
                ('Scale', StandardScaler())])

In [54]:
Cat_pipeline = Pipeline(
    steps = [
        ("Impute", SimpleImputer(strategy = "most_frequent")),
        ("Encode", OneHotEncoder(sparse_output=False))
    ]
)

Cat_pipeline

Pipeline(steps=[('Impute', SimpleImputer(strategy='most_frequent')),
                ('Encode', OneHotEncoder(sparse_output=False))])

In [55]:
preprocessor = ColumnTransformer(
    transformers = [
        ("Numerical", Num_pipeline, num_col_list),
        ("Categorical", Cat_pipeline, cat_col_list)
    ]
)

preprocessor

ColumnTransformer(transformers=[('Numerical',
                                 Pipeline(steps=[('Impute',
                                                  SimpleImputer(strategy='median')),
                                                 ('Scale', StandardScaler())]),
                                 ['longitude', 'latitude', 'housing_median_age',
                                  'total_rooms', 'total_bedrooms', 'population',
                                  'households', 'median_income']),
                                ('Categorical',
                                 Pipeline(steps=[('Impute',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('Encode',
                                                  OneHotEncoder(sparse_output=False))]),
                                 ['ocean_proximity'])])

In [56]:
Final_pipeline = Pipeline(
    steps = [
        ("Preprocess", preprocessor),
        ("model", LinearRegression())
    ]
)

Final_pipeline

Pipeline(steps=[('Preprocess',
                 ColumnTransformer(transformers=[('Numerical',
                                                  Pipeline(steps=[('Impute',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('Scale',
                                                                   StandardScaler())]),
                                                  ['longitude', 'latitude',
                                                   'housing_median_age',
                                                   'total_rooms',
                                                   'total_bedrooms',
                                                   'population', 'households',
                                                   'median_income']),
                                                 ('Categorical',
                                                  Pipeline(steps=[('Impute',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('Encode',
                                                                   OneHotEncoder(sparse_output=False))]),
                                                  ['ocean_proximity'])])),
                ('model', LinearRegression())])

In [57]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2)

In [59]:
Final_pipeline.fit(x_train, y_train)

Pipeline(steps=[('Preprocess',
                 ColumnTransformer(transformers=[('Numerical',
                                                  Pipeline(steps=[('Impute',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('Scale',
                                                                   StandardScaler())]),
                                                  ['longitude', 'latitude',
                                                   'housing_median_age',
                                                   'total_rooms',
                                                   'total_bedrooms',
                                                   'population', 'households',
                                                   'median_income']),
                                                 ('Categorical',
                                                  Pipeline(steps=[('Impute',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('Encode',
                                                                   OneHotEncoder(sparse_output=False))]),
                                                  ['ocean_proximity'])])),
                ('model', LinearRegression())])

In [64]:
y_pred = Final_pipeline.predict(x_test)

In [63]:
r2 = r2_score(y_test, y_pred)
print(f"R2 Score: {r2:.4f}")

R2 Score: 0.6516