<a href="https://colab.research.google.com/github/Deveshjd/ML-Notebooks/blob/main/ML1.0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# imputation --> filling the missing values

In [ ]:
# for nominal data --> one hot encoding
# for ordinal data --> ordinal encoder

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

# **Starting with ML**

In [ ]:
data = pd.read_csv("/content/housing 1.csv")

In [ ]:
data.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [ ]:
x = data.drop("median_house_value", axis=1)

In [ ]:
y = data["median_house_value"]

In [ ]:
cat_col_list = x.select_dtypes("object").columns.tolist()
num_col_list = x.select_dtypes(["int", "float"]).columns.tolist()

In [ ]:
print(cat_col_list)
print(num_col_list)

['ocean_proximity']
['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income']

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

In [ ]:
num_pipeline = Pipeline(
    steps = [
        ("Imputer", SimpleImputer(strategy="median")),
        ("Scaler", StandardScaler())
    ]
)

num_pipeline

Pipeline(steps=[('Imputer', SimpleImputer(strategy='median')),
                ('Scaler', StandardScaler())])

In [ ]:
cat_pipeline = Pipeline(
    steps = [
        ("Imputer", SimpleImputer(strategy='most_frequent')),
        ("Encoder", OneHotEncoder(sparse_output=False))
    ]
)

cat_pipeline

Pipeline(steps=[('Imputer', SimpleImputer(strategy='most_frequent')),
                ('Encoder', OneHotEncoder(sparse_output=False))])

In [ ]:
from sklearn.compose import ColumnTransformer

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ("numerical", num_pipeline, num_col_list),
        ("categorical", cat_pipeline, cat_col_list)
    ]
)

preprocessor

ColumnTransformer(transformers=[('numerical',
                                 Pipeline(steps=[('Imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('Scaler', StandardScaler())]),
                                 ['longitude', 'latitude', 'housing_median_age',
                                  'total_rooms', 'total_bedrooms', 'population',
                                  'households', 'median_income']),
                                ('categorical',
                                 Pipeline(steps=[('Imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('Encoder',
                                                  OneHotEncoder(sparse_output=False))]),
                                 ['ocean_proximity'])])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [ ]:
x_train

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
9429,-122.68,38.07,26.0,1445.0,244.0,510.0,207.0,5.6305,NEAR OCEAN
7862,-118.13,33.90,35.0,1458.0,261.0,686.0,236.0,3.9038,<1H OCEAN
6740,-118.09,34.12,38.0,1713.0,285.0,779.0,286.0,5.6152,<1H OCEAN
12967,-121.32,38.70,16.0,3592.0,642.0,1740.0,629.0,3.0703,INLAND
16710,-120.47,35.04,29.0,1315.0,279.0,926.0,249.0,2.9375,<1H OCEAN
...,...,...,...,...,...,...,...,...,...
4492,-118.22,34.06,52.0,48.0,6.0,41.0,10.0,10.2264,<1H OCEAN
10753,-117.89,33.61,44.0,2126.0,423.0,745.0,332.0,5.1923,<1H OCEAN
20521,-121.53,38.57,34.0,3395.0,592.0,1518.0,627.0,4.0833,INLAND
125,-122.22,37.85,28.0,5287.0,1048.0,2031.0,956.0,5.4570,NEAR BAY
15846,-122.43,37.75,40.0,4850.0,977.0,1824.0,952.0,5.0519,NEAR BAY

In [ ]:
y_train

9429     430000.0
7862     202700.0
6740     359900.0
12967    126000.0
16710    144800.0
           ...
4492     112500.0
10753    500001.0
20521    118500.0
125      337300.0
15846    356100.0
Name: median_house_value, Length: 16512, dtype: float64

In [ ]:
x_train_scaled = preprocessor.fit_transform(x_train)
x_test_scaled = preprocessor.transform(x_test)

In [ ]:
# preprocessor.get_feature_names_out()

In [ ]:
# pd.DataFrame(x_train_scaled, columns=preprocessor.get_feature_names_out())

In [ ]:
x_test_scaled

array([[ 1.16878833, -0.71204614,  0.02958255, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.84365089, -0.88553713,  0.18809857, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.64356632, -0.72611298,  0.42587259, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.79863186, -0.95118237, -0.92151353, ...,  0.        ,
         0.        ,  1.        ],
       [ 1.22381159, -1.36849852,  0.26735657, ...,  0.        ,
         0.        ,  1.        ],
       [-0.08174028,  0.50239076, -0.92151353, ...,  0.        ,
         0.        ,  0.        ]])

In [ ]:
x_train_scaled

array([[-1.55236193,  1.14008735, -0.20819147, ...,  0.        ,
         0.        ,  1.        ],
       [ 0.72360015, -0.81520295,  0.50513059, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.7436086 , -0.71204614,  0.74290462, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.97711877,  1.37453463,  0.42587259, ...,  0.        ,
         0.        ,  0.        ],
       [-1.32226467,  1.03693055, -0.04967546, ...,  0.        ,
         1.        ,  0.        ],
       [-1.42730907,  0.9900411 ,  0.90142063, ...,  0.        ,
         1.        ,  0.        ]])

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, confusion_matrix, accuracy_score

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(x_train_scaled, y_train)

LinearRegression()

In [ ]:
y_pred = model.predict(x_test_scaled)

In [ ]:
r2_score(y_test, y_pred)

0.6658879736034692

In [ ]:
confusion_matrix(y_test, y_pred)

ValueError: Classification metrics can't handle a mix of multiclass and continuous targets

In [ ]:
sns.heatmap(confusion_matrix(y_test, y_pred), annot=True)

ValueError: Classification metrics can't handle a mix of multiclass and continuous targets