<a href="https://colab.research.google.com/github/Deveshjd/ML-Notebooks/blob/main/working_with_datasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as mp
import pandas as pd
import seaborn as sns

In [2]:
data = sns.load_dataset("tips")
data

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [65]:
data["sex"].shape[0]

244

In [36]:
# How many male came on thursday
data[(data["sex"] == "Male") & (data["day"] == "Thur")].shape[0]

30

In [59]:
# Average tip given by all males
data[data["sex"] == "Male"]["tip"].mean()

np.float64(3.0896178343949043)

In [61]:
# No. of female smokers
data[(data["sex"] == "Female") & (data["smoker"] == "Yes")].shape[0]

33

In [67]:
# Average size of female group
data[data["sex"] == "Female"]["size"].mean(). astype(int)

np.int64(2)

In [68]:
# Average bill paid on sunday
data[data["day"] == "Sun"]["total_bill"].mean()

np.float64(21.41)

In [71]:
# Highest bill ever paid for dinner
data[data["time"] == "Dinner"]["total_bill"].max()

50.81

In [73]:
# Higest no. of smokers visited on which day
for i in data["day"].value_counts().index:
  print(f"{i} --> {data[(data["smoker"] == "Yes") & (data['day'] == i)].shape[0]}")

Sat --> 42
Sun --> 19
Thur --> 17
Fri --> 15

In [75]:
# compare no. of females visited for lunch and dinner
for i in data["time"].value_counts().index:
  print(f"{i} --> {data[data["sex"] == "Female"].shape[0]}")

Dinner --> 87
Lunch --> 87

In [76]:
# what time does the non smokers prefer(lunch, dinner)
for i in data["time"].value_counts().index:
  print(f"{i} --> {data[(data["smoker"] == "No") & (data["time"] == i)].shape[0]}")

Dinner --> 106
Lunch --> 45

In [ ]:
data[(data["sex"] == "Male") & (data["day" == "thu"])].value_counts()

In [28]:
for i in data["day"].value_counts().index:
  print(f"{i} --> {data[(data["smoker"] == "Yes") & (data['day'] == i)].shape[0]}")

Sat --> 42
Sun --> 19
Thur --> 17
Fri --> 15

In [37]:
data["size"].value_counts()

size
2    156
3     38
4     37
5      5
1      4
6      4
Name: count, dtype: int64

In [54]:
# sabse zyada tip male ne di ya female ne

data[(data["sex"] == "Male") & (data["tip"] == data["tip"].max())]["tip"]

# data["tip"].max()

170    10.0
Name: tip, dtype: float64

In [58]:
# sabse zyada smoking male ne kri ya female ne

for i in data["sex"].value_counts().index:
  print(f"{i} --> {data[(data["sex"] == i) & (data["smoker"] == "Yes")].shape[0]}")

Male --> 60
Female --> 33